libass/ass_bitmap.c
libass/ass_rasterizer.c
libass/ass_rasterizer.h
libass/ass_rasterizer_c.c
libass/x86/rasterizer.asm
libass/x86/rasterizer.h

Utilizing new alloc_bitmap_raw() function for rasterizer.
Not tested with AVX2.

Skip memset() when using internal rasterizer

---

libass/ass.c
libass/ass_render.c

I just ran clang's scan-build analysis on libass and it found some minor issues, most importantly a memory leak. These commits fix the problems reported.

Fix some issues reported by clang scan-build

---

libass/ass_bitmap.c
libass/ass_bitmap.h
libass/ass_render.c

Of particular note: as discussed in #9,
* VSFilter has pixel values in the range from 0 to 64 inclusive, while libass uses the range from 0 to 255. Normally this doesn’t matter at all. For \blur, this merely means VSFilter’s has banding. But for \be with a large iteration count, the output is very different. This pull request makes libass use the range from 0 to 64 for all \be iterations but the last. The range conversions are correctly rounded (towards positive infinity where relevant). If the \be argument is 1 or 0, no range conversion takes place. The last \be pass is done on the full range to smooth out the output to make better use of the full range and hide whatever little banding was introduced by the reduced range.
* Blurs, both \blur and \be, cause bitmaps to expand. All …

\be fixes including clipping and value range

---

libass/ass_directwrite.c
libass/dwrite_c.h

The fontselect merge introduced some MSVC compilation problems. This PR doesn't attempt to manage all of them because some fixes require more invasive changes.
Here's a list of things that are __not__ addressed in this PR:
- `ass_fontselect` uses iconv to convert UTF-16 to UTF-8. This makes iconv a hard dependency. `WideCharToMultiByte` works on Windows, but some abstraction is necessary for good cross-platform support.
- ~~`ass_fontselect` uses `PATH_MAX` which is undefined on Windows.~~ Fixed enough in master.
- ~~`ass_fontselect` uses `snprintf` which doesn't exist on windows.~~ This is fine with MSVC14.

MSVC fixes.

---

libass/ass_fontselect.c

This is a normal course of action and should not generate a warning,
especially for applications which use libass and might notify the user
on such "warnings", while in fact it should be info or even verbose.
Fixes #231

font load from dir: use MSGL_INFO instead of MSGL_WARN

---

libass/ass_render_api.c

I noticed that when resizing the mpv window while playback is ongoing
and with subtitles, that subtitles could sometimes get "stuck" on the
screen. The stuck subtitle would remain until the next subtitle event,
or until seeking to a position that has subtitles again.
It turned out that this was a libass change detection bug. The following
steps should reproduce the problem:
1. call ass_render_frame() with a time that has subtitles
2. call ass_set_frame_size() with a different size
3. call ass_render_frame() with a time that has no subtitles
The previous call will return with *detect_change==0.
To make this worse, libass will deallocate image data before the next
ass_render_frame() or ass_renderer_done(), which violates the API and
could possibly make some API users crash. (That the user …

render_api: do not discard old images on reconfiguration

---

libass/ass_render.c
libass/ass_render.h

That variable was workaround for case when new frame images
reuse memory from previous frame images. Due to that reuse
physically different images could be indistinguishable in
ass_detect_change(). After cache PR such memory aliasing is
no longer possible and workaround is redundant.

render: remove redundant has_clips

---

libass/ass_cache_template.h
libass/ass_render.c

An actual example of breakage that this PR should fix was reported on IRC: when `ScaledBorderAndShadow` is changed in Aegisub, no difference is visible because the old outlines are fetched from the cache.

Reflect border_scale in outline cache keys

---

libass/ass_bitmap.c

We're not aware of any specific reason for this number to be used,
and actual potentially-dangerous cases should be handled by the
other limits.
Fixes #260

Remove arbitrary bitmap size limit

---

libass/ass_directwrite.c
libass/ass_fontselect.c
libass/ass_fontselect.h
libass/dwrite_c.h

DirectWrite's FontFileStream does not actually use the data of a specific
font in a collection, which was an expectation of the existing code. It
simply returns a stream to the underlying file, collection or not. So we
need to get the index of the font. This needs to be done lazily as this
information is only available in a FontFace, which is expensive to
initialize.
Add a new optional font provider function for lazy initialization of the
index and use it. This is similar to the check_postscript callback.
Fixes libass#275.

directwrite: fix font collections

---

libass/Makefile.am

nasm always uses %include paths starting from the directory from where
it's started.
Fixes https://github.com/libass/libass/issues/282

x86: fix out-of-root builds after 8bddaa2a7

---

libass/ass_bitmap.c
libass/ass_bitmap.h
libass/ass_cache.h
libass/ass_cache_template.h
libass/ass_drawing.c
libass/ass_drawing.h
libass/ass_outline.c
libass/ass_outline.h
libass/ass_parse.c
libass/ass_rasterizer.c
libass/ass_rasterizer.h
libass/ass_render.c
libass/ass_render.h

This PR mainly do the following things:
- replaces `FT_Vector`, `FT_BBox`, `FT_Pos` with fixed size types based on `int32_t`;
- uses libass native coordinates in outlines instead of FreeType's reversed Y axis;
- simplifies outline internal format for more straightforward processing;
- consolidates similar types and functions from different files.
The main goal of this PR is to simplify code and there shouldn't be any difference in rendering results.

Update ouline internal representation

---

configure.ac
libass/ass_coretext.c

I remembered today that I had this lying around almost finished for two years. So I finally polished it to my liking, and well, here it is.
I know I’m probably the only one around here who cares about old OSs (and over the last two years this has gotten even less relevant than it once was), but hey, this change is not terribly complicated, is it?
I’ve been using this on Mac OS X 10.6 Snow Leopard for just over two years without any trouble.
The configure script could use `AC_CHECK_DECL`, and in fact my original version of this commit did exactly that, but then (a) behdad/harfbuzz#342 must be minded and (b) the message `./configure` prints on screen is `checking whether kCTFontURLAttribute is declared` (plus a second similar message on iOS), which makes it far from obvious that it’s …

Fix CoreText font provider in GCC and on old Mac OS X

---

Changelog
libass/ass_parse.c
libass/ass_parse.h
libass/ass_render.c

This prevents [stack overflow](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4892) on deeply nested `\t` by essentially performing tail call optimization on it.
The first commit indents the whole of `parse_tag`, so for viewing the diff, you probably want to use `git show -w` or `git log -p -w` on the command line rather than GitHub’s Web interface.
As we currently parse tags in a VSFilter 2.37–compatible way, parentheses are not parsed in nested pairs, but rather the very first closing parenthesis terminates the whole tag. So if you have a `\t()` inside another `\t()`, the first closing parenthesis terminates the outer `\t` and the inner `\t` actually doesn’t have a closing parenthesis at all. This means that if the parser ever encounters a `\t(` inside another `\t()`, it is the …

Reduce recursion and improve VSFilter compatibility for nested \t

---

libass/ass_render.c

That should help with DoS of events with huge number of \r.
I've not extensively tested that so I appreciate if anyone can test heavy override cases and such.

Speedup handling of multiple \r

---

libass/ass_coretext.c
libass/ass_font.c
libass/ass_font.h
libass/ass_fontconfig.c
libass/ass_fontselect.c

Some fonts have weights that can be expressed more precisely as doubles than as floats. In these cases, when writing to a float, CFNumberGetValue will set the value to the closest approximation, but return false (so we'd just clobber whatever it set with 0).
Easy fix: just store to a double instead.

coretext: fix reading weights of some fonts

---

libass/ass_coretext.c
libass/ass_fontselect.c
libass/ass_fontselect.h

This makes results much more consistent with other platforms, particularly around cases where fonts have multiple conflicting names.
A successor to #316, with name handling improved in addition to weight.

Use Freetype to read attrs on CoreText-discovered fonts

---

libass/ass_coretext.c

Fixes a crash in case a font does not has kCTFontURLAttribute,
which is the case for example on macOS 10.15.1 for the
".AppleSymbolsFB" font.
Fix #358

coretext: fix error handling in get_font_file

---

libass/ass_coretext.c
libass/ass_fontselect.c
libass/ass_parse.c
libass/ass_render.c

This previously gave the pre-transition value; VSFilter's behavior is to give the post-transition value.
hi @skiddiks

parse_tags: fix case where t==t1==t2

---

libass/ass_blur.c

Check for overflows that could happen with alignment and the
multiplication. The INT_MAX / 4 is somewhat approximate and assumes that
degenerate alignment values won't happen.
This still assumes that a possibly overflowing end_w/end_h calculation
doesn't make the compiler's optimizer destroy the overflow checks.
---
Sample at: https://github.com/mpv-player/mpv/issues/7435
This fixes a crash I encountered with the sample (at slightly below 4K display resolution), but doesn't fix much of the sample itself.

ass_blur: check for memory allocation size overflows

---

libass/Makefile.am
libass/ass.c
libass/ass.h
libass/ass_types.h
libass/libass.sym

This is a much discussed thing, that is supposed to enable us to disable
weird VSFilter compatibility hacks. Currently it obviously does nothing.
If we ever extend the libass format, the plan is that we may add a new
header to the ASS [Script Info] section, which causes the compliance
field set to a new (to be added) enum value.
In theory, we could reuse the track_type field for this purpose, but
that seems questionable. Better not touch anything related to SSA
compatibility.

Ass compliance field

---

libass/ass.c
libass/ass_coretext.c
libass/ass_fontselect.c
libass/ass_render.c
libass/ass_render.h
libass/x86/cpuid.h

Ran scan-build while poking around at clang-tidy and clang-format, and turned up some warnings. Some were false positives (but could easily be silenced in ways that improved code clarity); some were legitimate bugs. In the process, I ran into a couple additional bugs and went ahead and fixed them as well.

Static analysis warning fixes

---

compare/README.md
compare/compare.c

Padding should be 3 digits not 4, otherwise a time of eg `2252ms` is displayed as
`0:00:02.0252` instead of `0:00:02.252`.
Also updated `compare/README.md` accordingly.

compare: Fix millisecond formatting

---

libass/ass_render.c
libass/ass_render.h
libass/ass_render_api.c

Follow-up to #384 as discussed on IRC.
Like #384, this makes all affected subtitles fixed within the screen/window frame and unaffected by any further pan & zoom in the media player, and disables all of this entirely when `!use_margins`.
The difference is that elements are scaled to the same sizes they would be if the screen/window was displaying a fit-to-screen letterboxed video at 100% zoom & no pan, sans the black bars from letterboxing. For example, opening a 1920×720 video on a 1920×1200 screen and then going full screen keeps element sizes unchanged (except very slightly to adjust for the disappearing menu bars etc.). _(In mpv, element sizes are enlarged because it explicitly does this with its `--sub-scale-with-video` option. Use `--sub-ass-force-margins` and play ASS to see it in …

Fix & rework margins (black bars)

---

libass/ass_render.c
libass/ass_render.h

This pr changes implicit positioning to take Borders into account (like *VSFilter) and also changes the shift direction for `\an4,5,6` lines to match *VSFilter.
closes #304 
closes #143 
~~This pr is as of now not yet ready for merge.
However I'd would be niceto get some feedback if the chosen approach seems sensible.~~
--snip-- *(Moved the originally present/unidentified issues down as they have been adressed)*
As I couldn't locate the relevant part of VSFilter code, I relied on the info from #154 and test ASS files. VSFilter seems to only care about the maximal x-border, even if it's far from the edge of a line.
To test this pr I used these two ASS-Files
[Bord-Coll-ASS.zip](https://github.com/libass/libass/files/4638387/Bord-Coll-ASS.zip)
and …

Border collision and \an456 stacking

---

libass/ass.c

Being lenient about leading spaces will make invalid files as in #117 work with libass. As pointed out in #19 VSFilter is still far more lenient, but this patch improves it and would be neccessary for full compat anyway. fixes #117 
This was supposed to be a quick and easy fix.
However, while from libass' side this will make files as in #117 worrk, mpv will still refuse 117's sample file [(mpv-player/mpv/2846)](https://github.com/mpv-player/mpv/issues/2846) and with my synthetic test-file, mpv (or at least version 0.29.1-1 as packaged in Debian Buster) does some reordering that results in the first Dialogue line being not displayed (but parsed). This **does not** happen with `compare` or Aegisub, so it's not an libass issue.
*I can't test current git HEAD mpv right now, as it requires …

Ignore leading space of lines in parsing

---

libass/ass.c
libass/ass.h
libass/ass_priv.h
libass/ass_render.c
libass/ass_shaper.c
libass/ass_shaper.h

As shown in #374, bracket matching (introduced in commit df7c00c95ec6e526bf85e6bc8296eaca66f5db8d of #298, but not yet part of any release) is incompatible with VSFilter (even on modern Windows).
As decided in #374, disable it by default. But as bracket matching is generally a good thing (and simply more standards-compliant), keep it available as an ASS_Feature that can be enabled for things like media player UIs.
The new feature can be toggled individually or enabled as part of the catch-all `ASS_FEATURE_INCOMPATIBLE_EXTENSIONS`. I’ve removed the placeholder `enable_extensions` flag and instead directly toggle the new feature’s underlying flag when the catch-all is toggled.
If libass is compiled against FriBidi older than 1.0, bracket matching is impossible. Signal this at runtime by …

Disable bidi bracket matching unless enabled via ASS_Feature

---

libass/ass_cache.h
libass/ass_render.c
libass/ass_render.h

Some releases rely on this.
See corresponding VSFilter code: https://github.com/Cyberbeing/xy-VSFilter/blob/cf8f5b27de77fe649341bfab0fdfd498e1ad2fa6/src/subtitles/RTS.cpp#L1270

render: match cases where VSFilter doesn't paint fill in the shadow

---

libass/ass.h

Some of the API is declared to be deprecated in source comments, but this is easy to miss. Now GCC, Clang and MSVC should issue a warning when deprecated API is used.
---
Version checks for GCC are a bit messy. If supporting deprecation-warnings on versions older than GCC 6 is not important this can be simplified. *(For reference: 6.1 released 27.04.2016; Debian Jessie (oldoldstable) shipped 4.9.2, but LTS support ended a month ago)*  
Since I could not find out when clang gained support for the deprecation attribute (for enums), I'm assuming it will always be supported.  
Tested with clang7 and gcc8
**Not tested with MSVC**.
It'd be good, if someone with an MSVC compiler could verify that deprecation warnings are working. Otherwise I'd prefer to drop the untested MSVC part.
Here's a test …

ass.h: Mark deprecated declarations as deprecated

---

libass/ass_render.c
libass/ass_render.h
libass/ass_shaper.c

This isn’t perfect: VSFilter knows nothing about “skippable”/invisible characters. It works with opaque UTF-16 code units and treats specially only U+0020 SPACE and line breaks. A line height gets halved if the line contains no code units between two line breaks. So our whole `skip` business should not apply to line height calculations. But of course, we use `skip` during shaping and we use shaping during line wrapping… So this is a bit complicated.
This works well as an approximation though.

Line height fixes

---

libass/ass_outline.c
libass/ass_outline.h
libass/ass_rasterizer.c
libass/ass_render.c

I've added a couple of checks for overflows in outline pipeline. Should fix #431, but I'm not familiar with that fuzzing business so I can't ascertain it for now.

Fix overflows in outline processing

---

libass/ass_font.c

I think this is the most straightforward fix of #414.
I've tried to tinker with `desc` field of `ASS_Font` structure but that leads to much more ugly code.

font: use library as a failure flag

---

libass/ass.c
libass/ass_parse.c
libass/ass_strtod.c
libass/ass_utils.c

A bunch of integer overflow fixes plus a few other fixes that I made along the way.
Unresolved issues:
* Event timestamps can overflow `long long`. What should we do then? Saturate to LLONG_MIN/LLONG_MAX? This would be fine for the purposes of deciding which event to show when but could break animations that depend on the event duration. Then again, VSFilter doesn’t even support `long long` timestamps like we do. (It uses `int`. Which, of course, practically means `int32_t`.)
* When `PlayResY` is set (to a positive value) but `PlayResX` isn’t, it is computed as ⁴⁄₃ × `PlayResY`. This value may not fit in `int`. What should we do then? VSFilter does `PlayResY * 4 / 3` (all in `LONG` aka `int32_t`) and doesn’t care. I forget if I’ve tested what actually happens then.

Integer overflow fixes

---

libass/ass_parse.c
libass/ass_render.c
libass/ass_render.h

Both in one PR because the “Support Banner/Scroll effects with \pos/\move” patch assumes the clip coordinate conversion patch has been applied first.
Labelling this “cosmetic” for the clip coordinate patch; “compatibility” for all the rest.
All banner/scroll changes have been tested and verified in practice against xy-VSFilter and MPC-HC.

Fix Banner/Scroll effects & simplify clip coordinate conversion

---

configure.ac
libass/ass_render.c
libass/ass_render.h
libass/ass_render_api.c
libass/ass_shaper.c
libass/ass_shaper.h

Closes #199.
The hb-ft commit means harfbuzz no longer needs to depend on freetype to work with libass.
Also adds some missing malloc error checking.

Make harfbuzz a hard dependency

---

libass/ass_render.c
libass/ass_render.h

For a change from the alloc-stuff here's a small, cosmetic refactor.
---
Contrary to what the comments suggest Segment does not use one
absolute reference point and relative offsets, but two absolute points,
making it practically identical to the previously defined Rect with
a ≙ y0,  b ≙ y1,  ha ≙ x0,  hb ≙ x1
For simplicity, replace Segment with Rect.

ass_render: Replace Segment with Rect

---

libass/ass_outline.c
libass/ass_outline.h
libass/ass_parse.c
libass/ass_render.c
libass/ass_render.h
libass/ass_utils.h

OK, sooo…
* This makes karaoke quite sane in the common case where there are no 3D transforms, fixing our regressions and old bugs. So it should now mostly Just Work in practice.
* The behaviour of \kf may be surprising if the text has serifs extending far to the left or far to the right: the karaoke fill line instantly jumps to the first glyph’s origin point when karaoke starts, moves smoothly to the point where the next-beyond-last glyph’s origin would be, and instantly jumps to +infinity when karaoke ends.
* This makes karaoke more compatible with VSFilter, fixing our handling of edge cases, adding special cases that we didn’t handle at all, and reproducing VSFilter’s handling of karaoke on glyph run boundaries.
However, the various flavours of VSFilter handle \kf differently, and …

Karaoke fixes & improvements

---

libass/ass_render.c

Instead of calculating the intersection rect and testing for an zero area *(as VSF does)*, treating zero-area event's as fixed and otherwise keeping the current intersection code should yield identical results (while probably being a tad faster than VSF).
There's one more `shift_event` call which I didn't modify here: https://github.com/libass/libass/blob/700e131c78e6c917369c02161c4c8e2408d963e5/libass/ass_render.c#L3031-L3037
I'm not sure what this one does, but it seems to work without modifying this call.

Treat zero-area events like VSFilter

---

compare/compare.c
libass/ass.h
libass/ass_library.c

Both parameters are copied and are immutable. Make it clear through the
function prototype

ass_library: Constify ass_add_font

---

Makefile.am
configure.ac

Except for the first commit, all changes are purely cosmetic.
Commit 1 adds NASM support for Haiku and makes configure print an error when trying to use NASM on a supported architecture but unrecognised platform. *(currently it just silently produces borked files)*
The main cosmetic improvement of this PR is reodering the configure logic to be imo easier to understand. While doing so I noticed some odd bits; the last 3 commits remove these seemingly unnecessary parts. *(Please tell me if they did serve some purposes afterall)*
Configuration and *(non-static)* compilation was tested on Debian Buster, Debian Sid, OpenIndiana Hipster and Haiku R1/beta2.
---
Furthermore I'm planning to replace the bare shell control structures with proper Autotools-M4 macros and change the `configure.ac` …

Autotools Cosmetics: Part 1

---

libass/ass_outline.h

There is a small typo in libass/ass_outline.h.
Should read `outline` rather than `ouline`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, ouline -> outline

---

libass/ass_render.c
libass/ass_render.h

I'd misunderstood the vsfilter code in 12cf524b831289cf67ba3432264fa01a69c3bbb5 and written something that's very close, but not quite identical, to what it does. This should get us the rest of the way there.

ass_render: fix aliasing when 1a=0 but 3a>0

---

.github/workflows/ghci.yml

`travis-ci.org` will [close on 31.12.2020](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#q-when-will-the-migration-from-travis-ciorg-to-travis-cicom-be-completed) and `travis-ci.com` [does no longer offer MacOS builds to free users](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing).
Since the project is currently hosted on GitHub using GHA as a travis replacement seemed like the least amount of work.
Compared to our travis builds GHA is currently missing IRC notifications and Coverity.
To my knowledge there's unfortunately no easy way to get IRC notifications with GHA.
I don't think it's possible for me to migrate Coverity to GHA as I don't know about the tokens. @astiob, iimn your familiar with the Coverity stuff, could you take a look at if Coverity …

Use GitHubActions

---

configure.ac
libass.pc.in

Currently we mix bare shell parts with autoconf's M4-macros in configure.ac. And where M4-macros are used our style makes it easy to miss commas, which are crucial to functonality and missing them often won't result in errors as usually all but the first few parameters are optional. *(Also indents are inconsistent)*
My ideas to improve this are:
1) Better reflect shell constructs the macros will epxand to in linebreaks and indent levels.
This will hopefully also make it more obvious to the reader what the macros and parameters do.
2) placing commas on dedicated and/or same line as brackets they will be much harder to miss
and unbalanced brackets should cause noticeable errors.
3) Use (shell-)comments to fill in noops or for case-default etc *(should we use M4-comments (`dnl`, or a …

Autotools Cosmetics: Part 2

---

libass/ass_cache.c
libass/ass_cache_template.h
libass/ass_font.c
libass/ass_font.h
libass/ass_fontselect.c
libass/ass_parse.c
libass/ass_render.c
libass/ass_render.h
libass/ass_shaper.c
libass/ass_utils.h

I've removed most of strdups from rendering. Error handling should be simpler too.
There is a bunch of strdups in `ass.c` but that's impossible to remove without API change.
There is some concern that low-level parsing functions `mystrto*()` do not respect new string boundaries, but in our case we always have appropriate delimiter after string reference (`argto*()` rely on that too).

Reduce strdup() usage

---

configure.ac
libass/x86/rasterizer.asm
libass/x86/x86inc.asm

This should fix the warning introduced with nasm 2.15

x86: update x86inc

---

.github/workflows/ghci.yml
configure.ac
libass/ass_render.c

This could help us in future bug reports and we already do so for shapers and freetype.
Also include a guess about the source code version, which may not be entirely reliable, if custom tarballs are involved, commits are added after configure was called or if patches are applied without creating commits. But it may be good enough™ for most cases.
On the other hand this may lead us astray if any of the aforementioned are involved, not sure what's better. What are your thoughts on the "source version guess"?

Print libass version

---

libass/ass_blur.c
libass/ass_compat.h
libass/ass_render.c
libass/ass_utils.c
libass/ass_utils.h

Does not actually change our target to ISO C99 + POSIX `str(n)dup`.  
~~I'm not sure about putting `ASS_PI` into `ass_compat.h`, but couldn't come up with a better place for it.~~ `ASS_PI` has been moved to `ass_utils.h`

Improve ISO-C compatability

---

compare/compare.c
libass/ass.h
libass/ass_fontselect.c
libass/ass_fontselect.h
libass/ass_library.c
libass/ass_library.h
libass/ass_render.c
libass/ass_render.h
libass/ass_render_api.c
profile/profile.c
test/test.c

With this embedded fonts now work in VLC and our own utilities.
FFmpeg and Aegisub do not properly use `ass_set_extract_fonts`, so it still doesn't work for there *(but patching them should be fairly easy)*.

Fix embedded and memory fonts

---

libass/ass_render.c
libass/ass_shaper.c
libass/ass_shaper.h

Avoid the divisions by zero for \fscx0 and \fscy0. Regardless of the divisions by zero, avoid drawing any border. Two birds with one stone. Extra speed is a bonus.
~~Reset baseline everywhere that it should reset, rather than on the arbitrary condition that \fay must change.~~ in #441 now

Fix \fscx0, \fscy0 and a positioning bug with right-to-left \fay

---

libass/ass_coretext.c
libass/ass_coretext.h
libass/ass_directwrite.c
libass/ass_directwrite.h
libass/ass_fontconfig.c
libass/ass_fontconfig.h
libass/ass_fontselect.c
libass/ass_fontselect.h

Fixes #457.
Referring back to my list of options in https://github.com/libass/libass/issues/457#issuecomment-742155639, I ended up choosing a combination of (1) and (2) to preserve maximum compatibility with Windows font names. After all, there had to be a reason @rcombs changed the font name reads in the first place!

Core Text: fix font fallback, check allocations, reuse FT_Library

---

libass/ass_directwrite.c
libass/dwrite_c.h

scan_fonts can be very slow when many fonts were installed in
the system. Use IDWriteGdiInterop to create a font by its name
when needed instead of scanning all installed fonts during the
initializing stage to get better performance. In case of a
non-existent font, the fallback mechanism is supposed to do its 
work.(I am not sure about the consequences of removing 'scan_fonts',
but I think it should be ok.)

directwrite: request font on demand

---

libass/ass_directwrite.c

`match_fonts` is supposed to add all the fonts with the same family name for fontselect. The previous PR adds only one font, which leads to font with multiple styles cannot be correctly selected.

directwrite: fix `match_fonts`

---

README.md

Due to a change in effective control about the freenode network, most of its volunteer operators have left and founded [libera](https://www.oftc.net/) instead *(see eg this [resignation letter](https://fuchsnet.ch/freenode-resign-letter.txt) and eg [here](https://gist.github.com/joepie91/df80d8d36cd9d1bde46ba018af497409) and [here](https://lwn.net/Articles/856543) for more links with/and info)*.
This led many project to follow, eg [Wikimedia](https://meta.wikimedia.org/w/index.php?title=Wikimedia_Forum&type=revision&diff=21476411&oldid=21475994&diffmode=source), [Gentoo](https://www.gentoo.org/news/2021/05/23/Moving-to-Libera.html),   [Jellyfin](https://jellyfin.org/contact/#irc), [musl](https://musl.libc.org/), [SourceHut](https://sourcehut.org/blog/2021-05-19-liberachat/), [Void …

RFC: move IRC channel to libera

---

libass/ass_drawing.c
libass/ass_font.c
libass/ass_utils.h

This just cherry-picks the second and third commit (currently 4893db52623c85d37a7548401fc5738429de5537 and fbb12d1e0a948947e825ac85e758ca3c437bc34e) from rcombs' #506 so they can be included in 0.15.2.

Cherry-Pick Format fixes

---

libass/ass_coretext.c
libass/ass_fontconfig.c
libass/ass_fontselect.c
libass/ass_fontselect.h

As well as a couple of small fixes along the way (as often happens).
This preserves strict VSFilter-compatible explicitly-named-font choice on Core Text, DirectWrite and embedded fonts. (Localized names are problematic, but so they are in VSFilter.)
But when font fallback happens, the whole typographic font family will now be considered on Core Text and the best match will be chosen to match the active`\b` weight, even if the fonts’ GDI-compatible family names are different (e. g. Arial vs Arial Black, or Hiragino Sans W0…W9). This both achieves better visuals (although the ASS’s requested `\b` weight may be different from the main font’s actual weight…) and fixes Core Text fallback for good. In fact, this is how Core Text fallback worked before the font choice changes to make it more …

Font fallback: fix Core Text, enable future improvement

---

compare/README.md
compare/compare.c

That simplifies testing in case of multiple sets of target images for the same sub files. Also it's now possible to organize a pack of tests without font duplicating/symlinking trick.

Add support for multiple input directories for regression testing utility

---

.github/workflows/ghci.yml

Inspired by discussion in #523, here it is.
GHA's native Docker support isn't suitable for this, because it doesn't handle mixed non-Docker and Docker job variants well.
The `tail -f /dev/null` ~~hack~~method to keep the container running *(ignoring all zombie processes)* was ~~stolen~~learned from GHA's native Docker setup procedure.
The Docker setup relies on the current default of having the working dir and cloned repos somewhere in `/home/runner/work` and everything in the container will be executed as root.

ci/gha: add musl build

---

compare/compare.c

Without this `_mkdir` is undeclared on Windows:
```
CC       compare-compare.o
compare.c: In function 'main':
compare.c:27:27: warning: implicit declaration of function '_mkdir'; did you mean 'mkdir'? [-Wimplicit-function-declaration]
27 | #define mkdir(path, mode) _mkdir(path)
|                           ^~~~~~
compare.c:620:17: note: in expansion of macro 'mkdir'
620 |             if (mkdir(output, 0755)) {
|                 ^~~~~
CCLD     compare.exe
```

compare: fix _mkdir include on Windows

---

libass/ass_fontselect.c

There's no portable hard limit but `SIZE_MAX`. *(On POSIX systems `PATH_MAX` gives a soft limit, as a floor of which all applicatons on the system are expected to accept etc, but paths may theoretically also be longer; also `PATH_MAX` may be too large for the stack)*

fontselect: remove path length limit

---

libass/ass_font.c
libass/ass_fontselect.c
libass/ass_shaper.c

Supersedes and closes #508.
Implements stupid simple logic that seems to match Uniscribe/VSFilter somewhat, but perhaps not fully. At the very least, this should be a clear improvement over our current behaviour.

Don’t try to look up glyphs for invisible control characters

---

libass/ass_bitmap.c
libass/ass_bitmap.h
libass/ass_func_template.h
libass/ass_render.c
libass/x86/blend_bitmaps.asm

There should be `clip_func(src, clip) = iclip_func(src, 255 - clip)`, but our blending equations don't follow that. Also our clip function `sub_bitmaps()` is incorrect in case of half-transparent source and can lead to aliasing. So I've fixed it at the cost of a slight performance drop.

Make equations for \clip and \iclip complimentary

---

Makefile.am
libass/Makefile.am
ltnasm.sh

Closes #539; NetBSD was also affected.
Patch was tested on the following systems *(`y`: test successful; `-`: not tested,)*
|     *OS*     |  *Family*  |  ix86 | amd64 |
| ------------ |:----------:|:-----:| -----:|
| Alpine 3.14  | Linux-musl |   y   |   -   |
| Debian 11    | Linux-glibc|   y   |   y   |
| Haiku R1B3   |  BeOS-like |   y   |   y   |
| NetBSD 9.2   |    *BSD    |   -   |   y   |
| OpenIndiana  |   illumos/Solaris  |  y   |   y   |
@brad0 tested an earlier version on OpenBSD and our GHA CI will test on MacOS and Windows.

Use a libtool-wrapper script for NASM

---

configure.ac

Noticed JavascriptSubtitlesOctopus' libass builds didn't set the commit as source version; while at it also pulled in the config enhancements from #486.
Note, that even with this applied current JSO doesn't yet set the source version due to it copying the libass submodule to a different location for building, breaking the relative link to the real git-directory. This will be dealt with in a JSO-patch.

Configure: sourceversion in git submodules

---

libass/ass_bitmap.h
libass/ass_func_template.h
libass/ass_rasterizer.c
libass/ass_rasterizer.h
libass/ass_rasterizer_c.c
libass/ass_render.c
libass/x86/rasterizer.asm

Found buffer overrun (since assembly overhaul, I think) in rasterizer, but instead of an easy fix decided to go the long way and complete longstanding TODO.

Fix buffer overrun in rasterizer

---

libass/ass_drawing.c
libass/ass_font.c
libass/ass_font.h
libass/ass_outline.c
libass/ass_outline.h
libass/ass_render.c

The most strange for me was `FT_Get_Glyph()` call that looks totally unnecessary.
I've removed it in second commit, but maybe there's some hidden meaning in it?
On a side note: maybe we should extend lines by half pixel to mask gaps?

Follow-up for strikeout/underline commit

---

.github/ISSUE_TEMPLATE/crash.yml
.github/ISSUE_TEMPLATE/question.md
.github/ISSUE_TEMPLATE/wrong-rendering-report.yml

Saw this on GitHub and figured we might as well add one.
We somewhat often ask people to provide sample files. Another common problem is people showing `Dialogue` lines but forgetting `Style`. Finally, this will also remind people to check VSFilter if they can.

Create an issue template for incompatible rendering

---

libass/ass.c
libass/ass_priv.h
libass/ass_render.c
libass/ass_utils.h

The idea was proposed and first implemented in #481 and is supposed to scale better when adding future boolean-features. If we want to add non-boolean features at some point this might need to be changed again.
The implementation differs from #481's and also does not include a `ass_track_get_feature_state` API, as there were open question regarding handling of meta-features and about future non-boolean features. As long as we only have boolean features and all are initialised to false, I don't think `ass_track_get_feature_state` is strictly necessary yet.

Cosmetic: refactor track features to bitflags

---

.github/workflows/ghci.yml
configure.ac

First commit as suggested by astiob, though I'm not sure how far back the extra `--dirty` step works.
The "oldlib" container has almost the minimum version of all direct dependencies:
- FreeType2 `2.3.6`(external) - `9.17.3`(internal)
- HarfBuzz `1.2.3`
- Fontconfig `2.10.92`
- FriBidi `0.19.1` *(I couldn't find a tarball for `0.19.0` and there's no tag for it either; though the diff shows configure.ac used 0.19.0 at some point)*
As well as:
- automake 1.11
- autoconf 2.64
- gcc 6.3
- Debian Stretch's default version of `libpng` and `libexpat`, the latter being a transitive dependency
`docker_fetch` and `docker_image` allow to easily extend this to more purpose-built containers both from the same or other build-repo.
The build-recipe and binary for the container can be found here: …

ci/gha: bump to ubuntu-latest and dedicated "oldlib"-build

---

libass/ass_font.c
libass/ass_shaper.c

To resolve #531.
In case of non-Unicode cmap fonts, convert unicode code point(a UCS-4 code unit) to corresponding multibyte charset bytes, then assemble those bytes into a uint32_t, assuming those bytes present a prefix-zero-bytes-omitted big-endian integer. Freetype can make use of the converted code point to find correct glyph by non-Unicode cmap.
It introduces a dependency of `libiconv`. On Windows, `WideCharToMultiByte` is available to avoid libiconv if needed.
And I have just tested this patch on samples from #531 and #575, which covers BIG5 and SHIFT-JIS. For other encodings, I think it should work but I can't confirm. So further testing is needed.
#531 testing screenshot: 
#575 testing screenshot:

font: use iconv to handle non-unicode cmap microsoft fonts.

---

configure.ac
libass/Makefile.am
libass/ass_bitmap.c
libass/ass_render.c
libass/ass_utils.c
libass/ass_utils.h
libass/x86/cpuid.h

We detect x86* and enable building asm code in `configure`. However, we don’t actually use that code unless we detect x86* via the C compiler’s predefined macros.
Perhaps the best thing to do would be to set a `CONFIG_X86` flag in `configure` and check that. Shall we do that?
If not, here’s a patch that checks more macros to add support for:
* Microsoft Visual C++ (`_M_IX86`/`_M_X64`)
* Intel C++ Compiler for Windows (`_M_IX86`/`_M_X64`)
* Oracle Developer Studio (contrasts `__i386__` with `__x86_64` and sets `__i386` on both)
Subject to C99/C11/dependency support, this also supports:
* Digital Mars (`_M_IX86`, no 64-bit target)
* Watcom C/C++ (`_M_IX86`, no 64-bit target; defines `_M_IX86` also for 16-bit, but the `CONFIG_ASM` guard will block that)
* Stratus VOS/OpenVOS (`__i386`, no …

Use x86 asm code if we’ve built it, regardless of C compiler

---

libass/ass.h

The `NOTE:` at the end of `ass_set_storage_size`'s documenting comment matches how it is already done for `ass_set_fonts`. For better visibility this is again pointed out for both in `ass_renderer_init`'s comment.
I'm not sure if the phrasing for the anamorphic part is correct (or good).

Clearly document the need for ass_set_storage_size

---

libass/ass_render.c
libass/ass_utils.c
libass/ass_utils.h
libass/x86/blend_bitmaps.asm
libass/x86/cpuid.asm
libass/x86/cpuid.h

As discussed in #603 we need to check for cpuid support and if it is supported for the highest leaf available to avoid crashes and bogus results respectively.
The content of `ass_cpu_capabilities` is mostly copied from #400 and #559 but instead of using bitflags and moving it into a new / into the bitmap header it for now remains in `ass_utils`. It can be moved and switched to bitflags with the checkasm- and aarch64-related refactoring.
I'm still not 100% sure why x86_64 supposedly always supports cpuid, but gcc and [ffmpeg](https://github.com/FFmpeg/FFmpeg/commit/d05f808dc90a55f2a6eabe6ff62eb3a056e428d3) assume this *(x264 appears to have copied the check from ffmpeg; LAME only has 32bit assembly afaict)* and Zapeth’s guess about an implicit dependency SSE or so seems plausible.

Fix x86 cpuid

---

libass/ass.h

Possibly there's another issue with our description of `YCbCr Matrix: None` in `ass_types.h`.
Our docs claim and mpv interprets “None” to mean: “use sRGB values unchanged” and that this would match all but "some buggy" xy-VSF versions. However Cyberbeing’s and pinterf’s xy-VSFilter’s rc5 branches seem to effectively treat "None" the same as TV.601 afaict?
As mentioned on IRC we might want to deprecate setting PAR explicitly in favour of `ass_Set_storage_size` in the future *(and for `LayoutRes` it currently seems like ignoring the explicitly set PAR is required anyways)*. Does someone have a usecase for explicilty setting PAR with non-isotropic scaling?

Documentation Corrections 

---

libass/ass_drawing.c
libass/ass_parse.c
libass/ass_render.c
libass/ass_utils.h

This needs some discussion wrt VSFilter-compatibility and could probably be expanded to cover more casts not found in the samples yet; see commit messages. Reproducing samples here: [612_more-ub-fixes.zip](https://github.com/libass/libass/files/8498916/612_more-ub-fixes.zip)
Also see here for the tests probing what happens in practice on x86 WIndows for the relevant UB: https://github.com/TheOneric/libass/runs/6033094405?check_suite_focus=true#step%3A7%3A115=
@MrSmile: I haven't encountered such a sample yet, but from a quick glance it seems like the leftshift in `quantize_blur` can potentially end up with assigning -1 to the `shadow_mask` if the radius is so large that `ord > 31`. Would that be a problem or did I miss some guards protecting from this scenario?

Unsafe leftshifts and float cast overflows

---

libass/ass_render.c

See #610 for samples and VSFilter screenshots *(the assert fail in the `id:000159` samples is actuallly only fixed by #612 not this, which is why it is not listed in the commit)*.
Before this changes libass crashes if a Style with a negative `Fontsize` field is rendered either by failing an assert or if asserts are disabled by overflowing the stack. This brings the rendering closer in line with VSFilter and prevents crashes.
The change isn't fully correct though. Upon closer inspection the positive and negative fontsizes aren't quite identical in VSFilter (but would be with this change); the negative version is slightly **larger** than the positive one. I have no idea where this difference is coming from. At first glance the only bit affected by the sign of the fontsize in VSFilter is the …

Don't crash on negative Fontsize

---

compare/compare.c
profile/profile.c
test/test.c

As programs provided with the library's source code they also serve
as examples for how to correctly use the API, which usually means
setting a storage size.
- compare already sets the storage size.
- profile can continue using a fixed size, it never outputs the rendering.
- test already had issues before if either the guesses storage size was
incorrect or the frame size didn't match the intended aspect ratio.
To fixt both, add new optional arguments for storage and frame size.
Also fix rare `printf("%s", NULL);` bugs.

Set storage size in all utilities

---

libass/ass_render.c

Fixes #630  and a misrendering with hinting and `\fscy0`.
Afaict early exiting `fix_glyph_scaling` should give correct values and the rendering results do match my expectations.
However, for some reason this apparently changes the count of glyphs being loaded and errors occuring when loading glyphs in `ass_font_get_glyph` for `HINTING_NONE`. Using ` compare and an additional message before loading the glyph:
**WITHOUT PATCH**
HINTING_NONE:
```
libass: DEBUG: Try loading glyph 36 from face 0
```
HINTING_NATIVE:
```
libass: DEBUG: Try loading glyph 36 from face 0
libass: DEBUG: Try loading glyph 36 from face 0
libass: Error loading glyph, index 36
```
HINTING_LIGHT or HINTING_NORMAL:
```
libass: DEBUG: Try loading glyph 36 from face 0
libass: DEBUG: Try loading glyph 36 from face 0
``` …

Fix div by zero in fix_glyph_scaling

---

.github/workflows/ghci.yml
Makefile.am
configure.ac

UBSAN seems to have found something in our UWP build on `regression/karaoke/357-k-and-kf-desynced.ass`, thus the UWP failure. As MSys2 doesn't ship the supporting UBSAN library, there's no report indicating what the problem is though *(using `-fsanitize-undefined-trap-on-error` will cause SIGILLs (for Windows exit code 132) when something is found and allows the sanitiser to function without the library)*.
It would be good if someone can look into UBSAN’s findings; I don't see a way for me to investigate this myself. If nobody can, I'll probably just have to disable sanitisers for UWP.

Regression tests in make check, sanitisers in CI

---

libass/ass_parse.c

This caused animations to out-of-range alpha values to be clipped to the uint8_t range _before_ performing the lerp, rather than only after. VSFilter only truncates after. Using e.g. `\1a0\t(\1a1FF)` should run through the entire 0-FF range _twice_.

ass_parse: fix premature truncation on \t(\Xa)

---

configure.ac
libass/ass.c
libass/ass.h
libass/ass_library.c
libass/ass_render.c
libass/ass_render.h
libass/ass_shaper.c

Supersedes the inactive #372. *(GitHub: this closes #372, fixes #360)*
Adds an optional dependency on [libunibreak](https://github.com/adah1972/libunibreak) in order to get Unicode line breaking info.
In #372 the line break info got stored in a VLA, but with texts being arbitrarily long this seems too prone to stack overflows as most compilers I'm aware of allocate VLAs on the stack. To avoid frequent (de)allocations a shared scratch buffer is used instead.
Afaict the line wrapping should normally only happen once per event so there's no benefit in caching the line breaking info.
I'm not completely happy with how `WRAP_UNICODE` being enabled is rechecked for every glyph, but I don't think there's a way to avoid this without either duplicating the wrapping code or using function pointers. …

ASS Feature: WRAP_UNICODE

---

libass/ass_render.c
libass/ass_render.h
libass/ass_render_api.c

First commit is just a rebased from astiob’s [draft PlayResX fix](https://github.com/astiob/libass/commit/a550fc5115bd36cb9d0510976d7357b609410645). Afaict this is functionality-wise correct and was only missing the Effect `delay` unscaling. @astiob: Was this the missing thing you mentioned or is there something I overlooked?
Rebasing was mostly just moving things around, but also dealing with the newly emulated „shadow origin“ quirks, and dropping one change as the affected code was removed when the SBAS=no defaults were adjusted before 0.15.0.
One possible issue: anonymous unions used in this patch to alias `font_scale` and `screen_scale_y` are not part of ISO C99 our current baseline *(with some not documented machine assumptions)*. However, those are part of ISO C11 and prior to that …

PlayResX scaling and Effect’s delay precison and (non-)scaling

---

compare/image.c

Before (bad): https://github.com/libass/libass-tests/actions/runs/3480858990/jobs/5821196824
~~After (good): https://github.com/libass/libass-tests/actions/runs/3482692960/jobs/5825311965~~
After (good): https://github.com/libass/libass-tests/actions/runs/3488593779/jobs/5837608707

compare: fix 16-bit PNG read/write on big-endian platforms

---

libass/ass.c
libass/ass.h
libass/ass_priv.h
libass/ass_render.c
libass/ass_types.h

@Cyberbeing, @pinterf, @clsid2:
We would like to propose a retroactive addition to the ASS/SSA format, but in order to not fracture ASS even more we will only move forward with this if this extension will also be accepted and implemented in (most) active VSFilters.
This retroactive addition should be able to provide tangible benefits, while avoiding undue issues.
Some background first:
Rendering of the ASS/SSA format depends on the **video’s** *storage* resolution for several effects. This means subtitle releases are bound to a specific video (storage) resolution and in general cannot be reused for e.g. later BD-source releases of a higher resolution or in case of DVD-sources, different encodes which did/didn't undo the anamorphic stretching. *(Simple, sparingly styled subs may happen to …

ASS/SSA Format: Introduce LayoutRes{X,Y} script headers to allow easy multi-resolution releases

---

libass/ass_font.c

@rcombs You introduced the code in `ass_get_font_weight` in https://github.com/libass/libass/pull/316/commits/6c4dca2c8ed20d02ac877d55fe25d7db13ace615, but it wasn’t consistent with our pre-existing uses of the OS/2 table, so this makes them consistent. I don’t think the `version != 0xffff` check does anything useful. I’ve tried to guess why you may have originally included it; see the commit message: does that sound plausible?
Cc @moi15moi: you’ve asked me about the version check.

Simpler OS/2 table access

---

libass/ass_font.c

- Match GDI's special-case behavior for font weight values from 1 to 9.
- Match GDI's italicization transform matrix.
Both issues are demonstrated in the attached file:
[With_Jester.mkv.zip](https://github.com/libass/libass/files/10475605/With_Jester.mkv.zip)
This font used has weight 5.
[Jester Original.ttf.zip](https://github.com/libass/libass/files/10475612/Jester.Original.ttf.zip)
VSFilter rendering:
Current libass rendering (faux-bolded unnecessarily; sheared roughly 12 degrees rather than vsfilter's 20):
With this PR (perfect match):

Improve weight and faux-italic compatibility with VSFilter

---

libass/ass_cache.c
libass/ass_render.c

- Charge byte-based cashes for their CacheItems
- Note: we could also improve accuracy here by charging for alignment overhead, but I'd expect that to be a fairly small (and mostly constant) overhead compared to the others here.
- Charge the composite cache for the BitmapRef objects it owns
- Charge the bitmap cache for its OutlineHashValue
- The outline cache is also charged for this, but only per-glyph (not per-byte), and the bitmap cache can easily cause a large number of large outlines to be kept in memory far longer than the outline cache alone would.
The last commit is the most important here. On a sample with extensive use of the font "DINk", I see total memory allocated-and-persistent from ass_render_frame drop from 310MB to 180MB. This also results in the memory usage stabilizing …

Improve cache size accounting

---

configure.ac

After testing myself and searching through build logs, it looks like nothing needs `$host_vendor`. So let’s just use `$host_os`.
System          |    $host_os    |   vendor (example) | full $host | Comment
--------------- | -------------- | ------------ | --------- | -------
glibc-Linux     | `linux-gnu`    | `pc` | `x86_64-pc-linux-gnu` | Debian 11
x32 glibc-Linux | `linux-gnux32` | `pc` | `x86_64-pc-linux-gnux32` | Debian Sid
musl-Linux      | `linux-musl`   | `pc` | `i686-pc-linux-musl` | Alpine Linux 3.16
illumos         | `solaris2.11`  | `pc` | `x86_64-pc-solaris2.11` | OpenIndiana Hipster
Haiku           | `haiku`        | `unknown` | `x86_64-unknown-haiku` | Haiku R1/beta4
kFreeBSD        | `kfreebsd-gnu` | `pc` | `x86_64-pc-kfreebsd-gnu` | from Debian [build …

configure: use $host_os to detect NASM config

---

.gitignore
Makefile.am
Makefile_util.am
checkasm/arm/checkasm_64.S
checkasm/be_blur.c
checkasm/blend_bitmaps.c
checkasm/blur.c
checkasm/checkasm.c
checkasm/checkasm.h
checkasm/rasterizer.c
checkasm/x86/checkasm.asm
configure.ac
libass/Makefile_library.am

Leftover from my checkasm branch. Changes from my previous version:
- updated to current dav1d source (`readtime` for macos is already there, so one less thing to worry);
- simplified rasterizer check (no copy-paste from actual rasterizer code).
As for `BENCH_RUNS` count, I feel that it's not enough: even with `(1 << 16)` and `rdtsc` from x86 there's quite large variation in results. I think the whole timing logic should be modified. Currently it's
```c
uint64_t tsum = 0;
int tcount = 0;
for (int ti = 0; ti < BENCH_RUNS; ti++) {
uint64_t t = readtime();
test_func(...);
test_func(...);
test_func(...);
test_func(...);
t = readtime() - t;
if (some_black_magic) {
tsum += t;
tcount++;
}
}
```
Basically, it's 4 inner timed iterations plus `BENCH_RUNS` outer iterations with "clever" averaging of …

Checkasm v2

---

configure.ac
libass/ass_coretext.c
libass/ass_fontselect.c
libass/ass_fontselect.h

This should fix #595 and further make the Core Text system font provider usable on Mac OS X 10.5 “Leopard”—because why not?
@TheOneric Do we have any tests on PostScript-name vs full-name font selection? Looks like not? I don’t think it’s in any way urgent or a blocker for this, but at some point we probably should add some. And it would be great to have some tests targeting specifically system font providers, although I’m not quite sure how we could do that.

Support Core Text on Mac OS X 10.5 and prerelease 10.6

---

libass/ass_render.c
libass/ass_render_api.c

The more general version of 358770835248e26241e4796f38f02073a3bae252.

render_api: limit resolutions to be representable in a single ASS_Image

---

libass.pc.in

Minor cosmetic thing. After asking on IRC it seems like nobody still uses “LibASS”, so let’s be consistent.
Changelog entries for 0.9.5 and 0.9.6 are left as “LibASS”, otherwise this was the only remaining occurrence of “LibASS”.

Adjust spelling of libass in pc file

---

libass/ass.c

This matches VSFilter and avoids signed overflows for ABIs with 64bit `int`s, like ILP64.
In practice the latter is probably only a theoretical concern atm and this change more cosmetic.
Still, it amkes the intent clearer and matches how we’re moving more and more `int` to explicit `int32_t`.
My only concern comes from a vague memory, that `inttype.h` print/scan macros may sometimes under certain conditions *hurt* portability with some Windows compilation settings or so. @astiob, iinm this was something you brought up/discovered once, do you recall more and if this is applicable here (or am I just confused and mixing things up)?  
Though we already use `PRId64` further down in `ass.c`.

ass: explicitly read 32bit ints on timestring parts

---

README.md

Hopefully having a proper guide with all modern recommendations will help to prevent more broken ASS from being generated *(as e.g. happened before with FFmpeg)*.
This has been discussed on IRC before, though I also extended the Style notes a bit since because Aegisub’s manual doesn't specify the in-file representation of values. See: https://github.com/libass/libass/wiki/ASS-File-Format-Guide/_compare/2b0a8387ebe543dbcd897db6efed2e7fe644341a...678350f140d458f148990f66f6bd17992255ada7

readme: replace erroneous pseudo spec

---

libass/ass_drawing.c
libass/ass_drawing.h

This adjusts us to current VSFilter behaviour and is one approach to fix #719 
We know this will affect (at least, but from an extensive search *only*) two original typesets, but they aren’t degraded tooo badly.
Since we didn't find *any* samples broken by accepting such drawings, patching VSFilters instead to accept them was also suggested as an alternative on IRC. If done this would codify our somewhat odd existing behaviour on m-less drawings, but no files would be broken.
If someone wants to pursue the VSFilter patch approach, I have no objections to that and we can close this PR once that’s ready. Personally, I think it’s probably fine to degrade those two samples and adopt VSFilter’s current and imho more intuitive behaviour. Either way though, I think we shouldn’t put this off too …

Reject drawings not starting with m

---

libass/ass_directwrite.c
libass/ass_directwrite_info_template.h

DirectWrite sometimes returns names that differ from GDI’s. Instead of trusting it, use our own code that’s meant to be GDI-compatible, even if it costs us some extra resources.
This fixes https://github.com/libass/libass/issues/675 and facilitates future improvements to long font name matching (https://github.com/libass/libass/issues/459).
Plus a few minor improvements/precautions for exotic fonts/situations where we fail to find the same family name as DirectWrite does (or any family name at all).
Tested lightly: “Manrope Regular” works, and the added non-IDWriteFontFace3 code path works.

directwrite: read metadata on our own, use DirectWrite-reported name as fallback

---

libass/ass_types.h

Followup to the IRC discussion preceding and https://github.com/mpv-player/mpv/issues/13381 itself.
I’m not sure I got the terminology quite right, please check.
The YCbCr section in the file format guide prob also needs some tweaking. Perhaps something like **(changed section emphasised)*?:
> **YCbCr Matrix**
>
> [...]
> 
> Following these instructions will ensure, the final colours effectively exactly match the sRGB values specified in ASS. Diverging from this, will lead to **unmapped** colours being mangled as described in ass_types.h. **(But colour primaries and tone mapping will always follow the video colourspace regardless)**

Document tonemapping beyond RGB mangling

---

libass/ass_drawing.c
libass/ass_drawing.h

Our old code deviated from VSFilter in many ways (as discussed in #726) but this should (if I didn’t miss anything) align it with VSFilter. While this already leads to visibly different result in some cases, I don’t think any of the currently open vector drawing issues are fixed by this alone yet.
I decided to replace the whole tokenisation loop in favour of making the final result more readable, although this unfortunately makes the individual compat issues being fixed less visible in the diff. They are spelled out below:
- VSFilter ignores invalid commands together with their coordinates. Prior to this, libass ignored invalid commands itself but appended their coordinates to the preceding valid command. This was even intentionally exploited to (not-)implement p, resulting in different …

drawing: tokenise vector drawings like VSFilter

---

libass/ass_types.h

Revises #735 based on practical experience from mpv and further discussion summarised in https://github.com/libass/libass/issues/297#issuecomment-1991497184
Note:
- ~~the wording implies HDR subs will never be subject to `YCbCr Matrix` colour mangling; this isn’t explicitly stated in the linked comment but was suggested before and seems sensible~~
- this behaviour is now fixed for all current subs and will only change once files opt-in future HDR mechanisms
- this leaves the exact choice of SDR space implementation defined; if *(as some seemed to prefer)* we instead want to choose one single blessed colourspace, [mpv’s current choice](https://github.com/mpv-player/mpv/blob/6179995dd7ef576073e184abd01fd34890e1b59f/video/out/vo_gpu_next.c#L359-L362)  may be a good candidate

Update documentation re subs on HDR

---

fuzz/ass.dict

The fuzz dictionary was missing the new headers for LayoutResX and LayoutResY. I simply added them.

Add LayoutResX and LayoutResY to fuzz ass dict

---

.github/workflows/ghci.yml

It looks like `-latest` is only just now updating from 12: https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/
The 12 and 13 runners are Intel, while 14 is arm64. Once `-latest` is reliably 14, we can switch back to using that, but keep the 13 runner for Intel.

ci/gha: run on arm64 macOS

---

.github/workflows/meson.yml
.gitignore
Makefile.am
README.md
gen_defs.py
libass/ass/meson.build
libass/meson.build
meson.build
meson_options.txt
profile/meson.build
test/meson.build

Opened the PR for feedback despite a few remaining things that need to be cleaned up. The biggest benefit of this over autotools is that it enables easy compilation with MSVC, avoiding the need for a manual solution file which is difficult to maintain.
---
Not-CoffeeFlux here, since this PR went on for quite a while and GitHub likes to hide comments not near the start or very end, i’ve taken the liberty to edit details about the current status here for better discoverability *(mostly based on an updated version of [this comment](https://github.com/libass/libass/pull/330#issuecomment-1847988603)):
- drop global `cpp_std`
- use built-in NASM support
- Future-deprecated features used: `* 0.64.0: {'copy arg in configure_file'}`
- https://github.com/libass/libass/pull/330#discussion_r1399568357 …

Port of the build system to meson

---

libass/ass_filesystem.c

Since ASS_WINAPI_DESKTOP has been centralized, we don't need to include ass_directwrite.h anymore. We only need to include ass_compat.h

[ass_filesystem] Remove unused include

---

libass/ass_font.c
libass/ass_font.h
libass/ass_fontselect.h
libass/ass_shaper.c
libass/ass_shaper.h

Changes to `ass_shaper` made during work on #636 which don't require threading/atomics/locks:
- Keep the `hb_buffer_t` around between calls (it turns out to be fairly expensive to free and re-create in some cases)
- Create the `hb_font_t` eagerly during `add_face`
- Some consolidation of how we access the `FT_Face` and other data during font callbacks
The later changes are required for efficient access to the font object during shaping when running multi-threaded (they allow us to use lock-free cacheing for reads, which avoids most of the locking overhead around the `FT_Face` that we'd otherwise see).

ass_shaper improvements extracted from threading PR

---

libass/ass_drawing.c
libass/ass_drawing.h

This is the easiest part of our drawing discrepancies and _partially_ fixes the "s ... s ..." case from #202. However the upper left dip is still round and small, instead of a long spike. This probably comes from an unrelated difference in shape closing.
Plus some more cleanup
Relevant [VSFilter code](https://github.com/pinterf/xy-VSFilter/blob/45917d77083d93215738efb140486aba7614947e/src/subtitles/Rasterizer.cpp#L3303-L3309) for reference
Before, After, VSFilter *(from #202)*

drawing: implement EXTEND_SPLINE

---

libass/ass_font.c
libass/ass_font.h
libass/ass_fontconfig.c
libass/ass_fontselect.c
libass/ass_fontselect.h

Fixes #437.
This emulates GDI's behavior, both around scoring and faux decisions.
The fontconfig provider doesn't provide the full information we'd need to handle this 100% accurately, so it's best-guessed.
This branch is on top of #676, basically just to avoid rebase issues.

fontselect: overhaul font scoring and faux-ing

---

libass/ass_font.c
libass/ass_font.h
libass/ass_fontselect.c

#676 previously adjusted our faux italics to match GDI/VSFilter on TrueType fonts, but we later discovered that PostScript-outline fonts behave differently (font driver differences strike again) and our rendering became _less_ similar to VSFilter’s after that change. This should fix it.
I derived the coefficient experimentally using Fansub Block. The first-approximation value I got was awfully close to 10° (9.998°), so I figure it’s probably exactly 10°. Thus, I’ve hardcoded the closest fixed-point representation of tan(10°) in this commit.
TrueType:
PostScript:

Match VSFilter’s faux italics on PostScript-outline fonts, too

---

checkasm/checkasm.c
checkasm/checkasm.h
libass/x86/x86inc.asm

https://code.videolan.org/videolan/x86inc.asm/-/commit/b6ba1e3045d758fd6c6e24591dac21a3dc812e1d approaches the issue more broadly and replaces 0a63b95ce6dbe6fc3a6470c8b88b242341c8f961

Replace checkasm Haiku build patch with upstream solution

---

libass/ass_filesystem.c

```
In function 'open_dir_wtf8',
inlined from 'ass_open_dir' at ../libass-0.17.2/libass/ass_filesystem.c:339:9:
../libass-0.17.2/libass/ass_filesystem.c:325:8: warning: 'add_separator' may be used uninitialized [-Wmaybe-uninitialized]
325 |     if (add_separator)
|        ^
../libass-0.17.2/libass/ass_filesystem.c: In function 'ass_open_dir':
../libass-0.17.2/libass/ass_filesystem.c:305:10: note: 'add_separator' was declared here
305 |     bool add_separator;
```
`add_separator` will never be used uninitialized as the function starts with the assert. But that's not ideal nonetheless.

ass_filesystem: Fix add_separator compilation warning 

---

libass/ass_parse.c

I don't have a sample that's affected by this, but I'd expect it to be a little faster in some cases relating to clips. Hard to imagine this *hurts*, at any rate.

ass_parse: use memchr in ass_parse_tags

---

libass/ass_fontconfig.c
libass/ass_fontselect.c
libass/ass_fontselect.h

Based on IRC discussion an alternative to #777.
Posted as a new PR to make it easier to compare both approaches
Notably this adds language as a sorting parameter, which our existing `cache_fallbacks` logic makes an explicit effort to remove, but discussion in the RedHat issue linked from #737 suggests we might actually want this.
Also this omits any `FcConfigSubstitute` calls even though Fontconfig docs require it
Given the question of efficiency (re repeated width queries) was raised over in #777: i’d expect, but haven’t verified, this approach to be more perf costly given it does more (than we actually need). Not sure if the impact is relevant though

fontconfig: query a sorted list

---

configure.ac

Fixes detection for nasm when using slibtoolize instead of GNU libtoolize.
Fix from chimera-linux: https://github.com/chimera-linux/cports/commit/fa524593a52c057fe30215245298c2913a729ff6

configure.ac: add missing AC_CANONICAL_HOST

---

libass/ass_cache.c
libass/ass_cache.h
libass/ass_font.c
libass/ass_parse.c
libass/ass_render.c
libass/ass_shaper.c

I'm continuing to break up #636 into more-digestible chunks. This is a small portion of the changes to cache infrastructure, but includes the bulk of the changes to the cache's actual externally-visible behavior, which will make other chunks easier to break out from here.
- Remove unused stats functionality
- Don't increment refcount on cache hits

Cache changes extracted from threading PR

---

Makefile.am
Makefile_util.am
checkasm/be_blur.c
checkasm/blend_bitmaps.c
checkasm/blur.c
checkasm/checkasm.c
checkasm/checkasm.h
libass/Makefile_library.am

Take this PR more as a place for discussion about the right approach rather than pushing for the approach of the current patch
The simple way to fix this: just don’t run `checkasm` if there’s no static lib. *(what this PR currently does)*
iirc, originally (before merge) all relevant libass source files were also included in checkasm sources and there was no library link. This would have avoided this issue but introduced possible mismatches between lib and checkasm compile flags and thus changed.
To avoid both we could build just the bitmap engine + assembly as a always static-only internal lib and reuse it for checkasm. ~~However, at first glance I’m not sure how to tell libtool to build a library always static and if we use regular automake static libs, some flags (like PIC) might not be …

Deal with shared-only checkasm

---

libass/ass.c
libass/ass.h
libass/ass_library.c

We constified memory font data before in #448. Prompted by running into filepaths not being `const`, this now constifies most `char*`-related API paramters if they’re already effectively treated as const anyway and the new signature is pointer-compatible with the existing one.

Constify API parameters where possible

---

.github/workflows/meson.yml

Should save a lot of CI time on rebuilding all the wrapdb stuff.

ci/ghi: use pacman deps for MSVC builds as well

---

libass/Makefile_library.am
libass/ass.h
libass/ass_library.c
libass/ass_types.h
libass/libass.sym

These are simple wrappers around the libc malloc/free routines. Exposing them allows for safe heap usage across shared library boundaries in cases where there may be multiple instances of the libc functions present in the same process (e.g. libc statically linked into a shared lib). This mostly affects Windows.

ass_utils: add ass_malloc and ass_free routines

---

libass/ass_cache.c
libass/ass_cache.h
libass/ass_cache_template.h
libass/ass_render.c
libass/ass_render.h
libass/ass_shaper.c
libass/ass_shaper.h

More extracts from #636. This is on top of #783.

Cache per-size metrics in shaper

---

Makefile.am
configure.ac

This lets us check for warning flags at configure-time, avoiding introducing errors if a compiler doesn't support a particular flag.

build: move warning flags to configure.ac

---

libass/ass_fontconfig.c

When the used config is completely devoid of fonts, FcFontSort will attempt to allocate an empty set and return it but still set the result to be invalid.
Fortunately this seems unlikely to affect any real-world setups, but we should handle it correctly nevertheless.
Identified-by: kasper93

fontconfig: fix minor memory leak

---

Makefile_util.am
fuzz/fuzz.c
fuzz/writeout.c
fuzz/writeout.h

This was useful for OSS Fuzz’ timeout sample from 2 years ago and again for the  current one to figure out what’s (not) going on, so here’s a cleaned up version. Of course, if we actually have an infinite loop or very expensive operation in initially parsing, the writeout won’t halt (in reasonable time) either but this in itself already provides some insight

fuzz: allow outputting parsed file content

---

configure.ac
meson.build

With `-Wpedantic` instead to also cover GCC, we get three warnings about missing `(void *)` casts for printf arguments in both GCC and clang *(since different pointer types are allowed to have different representations, `%p` only taking `void *` and due to varargs no implicit cast can occur)*. While afaik no modern arch actually has different representations, the warning is entirely valid and easy enough to fix; imho we should add a cast here.
Only with GCC we additionally get 5 instances of `invalid use of pointers to arrays with different qualifiers in ISO C before C2X`. I haven’t looked into this but C23 adopting this as safe suggests there might not be much of at all problems in practice.
If `-Wpedantic` continues to be too contentious, we can at least enable this warning for clang; …

build: warn about non-ISO format strings with clang

---

libass/meson.build
meson.build

1. Redefining the meaning of `cpu_family` is a bit confusing, and unnecessary
2. Now setting `-Dasm=enabled` will error out early, so people know exactly what is wrong
3. When erroring out due to platform support, print the platform name

meson: Add support for android, simplify some nasm detection logic

---

compare/image.c
test/test.c

We discussed this a while ago in IRC wrt how creation of new regression tests can be made easier. With this patch a 320×180 reference image at 1000ms can be generated by running `~1/test sample-1000.png sample.ass 1000  320 180`.
Without this patch first a placeholder image with the desired dimension needs to be created, then `compare` run with output enabled.
(The latter used to be even more painful since only limited input formats were accepted and regenerating reference images needed manual ``compare` invocation. #767 and https://github.com/libass/libass-tests/pull/5 already made this easier)
However, there are caveats considering our utilities also serve as examples for API users and `test` is/was the most approachable one actually blending images:
1. unless i’m missing an obvious …

Use transparent background in test’s output images

---

libass/ass_bitmap_engine.h
libass/ass_utils.h
libass/c/blur_template.h
libass/c/c_be_blur.c
libass/c/c_blend_bitmaps.c
libass/c/c_blur.c
libass/c/rasterizer_template.h

First 3 commits of #749, rebased, as brought up by #819. Changes:
- `restrict`-qualify pointer args to all our C bitmap-engine functions
- These never alias, and letting the compiler know that allows it to skip emitting some unnecessary defensive code
- Add an `ASSUME` macro
- This tells the compiler that it can assume a particular expression will always evaluate to true, which can help it optimize more effectively (especially when autovectorizing)
- Use `ASSUME` to signal some trivial invariants in bitmap-engine routines
- Stride is always 16-byte-aligned, width/height are never zero (or 1, for be_blur), etc

Restrict-qualification + ASSUME macro usage in bitmap engine

---

libass/ass_bitmap_engine.h
libass/c/blur_template.h
libass/c/c_be_blur.c
libass/c/c_blend_bitmaps.c
libass/c/c_rasterizer.c
libass/c/rasterizer_template.h

I think explicitly specified pointer alignment can be beneficial too.
Also we should definitely replace `ASSUME` with `assert` for CI builds. I.e.
```c
#ifdef TESTING
#define ASSUME(x) assert(x)
#elif __has_builtin(__builtin_assume)
#define ASSUME(x) __builtin_assume(x)
#elif defined(_MSC_VER)
#define ASSUME(x) __assume(x)
#elif __has_builtin(__builtin_unreachable)
#define ASSUME(x) if (!(x)) __builtin_unreachable()
#else
#define ASSUME(x) (void) 0
#endif
```
We can reuse the same define later for threading cache asserts too.

ASSUME: tighten assumptions even more

---

checkasm/be_blur.c
checkasm/blend_bitmaps.c
checkasm/blur.c
checkasm/checkasm.c
checkasm/rasterizer.c
libass/ass.h
libass/ass_coretext.c

Addresses:
- NetBSD build failure ([see successfull CI run](https://github.com/libass/libass-tests/actions/runs/10931149065/job/30345770911))
- Superfluous include mentioned brought up in [commit comments](https://github.com/libass/libass/commit/abc7fbdbb0313536d2f9684dd527c736814e45d8#commitcomment-146703972)
- potential doc confusion brought up by astiob on IRC

Small tweaks

---

libass/Makefile_library.am
libass/ass.c
libass/ass.h
libass/ass_priv.h
libass/ass_render.c

An attempt to address #747, and to manage bloated scripts embedded in mkvs, like DataHoarder's. 
Motivations supporting the proposed solution:
- The default behaviour matches the current one: no collection is ever performed. It has to be explicitly enabled.
- The user is free to prune events at will, or rely on the automatic process after every render.
- Can be configured per track.
Point open for discussion:
- The prune function is not thread safe [to changes made to the events array].

Add event pruning system and API.

---

libass/libass.sym

Fixes: dcc9eb722ebd485d2ed0e21c261b0a1b05497154

libass: export ass_{prune_events,configure_prune} symbols

---

libass/aarch64/blend_bitmaps.S
libass/aarch64/blur.S
libass/aarch64/rasterizer.S

The align parameter to these macros is passed to the gas directive .align. This directive is architecture dependent; on some architectures, the given alignment is an alignment in bytes, while on others, its the power of two to align to. On aarch64, .align is for power of two alignment, see [1] for details; i.e. it behaves the same as .p2align.
This means that when the macros are invoked with align=16, we actually requested 64 KB alignment, not 16 byte alignment. Fix this, setting the alignment to the intended 16 byte alignment.
This fixes building for aarch64-windows targets with assert enabled versions of Clang; such versions of Clang error out with "unsupported section alignment" on this case, while regular release versions of Clang silently let this issue pass.
[1] …

aarch64: Set the right intended alignment for constants

---

Makefile.am
configure.ac
meson.build

If someone figures out how to sidestep the array type incompatibility in C99 without additional copies, we can also use `c99` everywhere instead.

Consistent C standard and feature flags

---

libass/ass.h

The existing comment described the bitmap as being "1bpp", which is commonly understood to mean "1 bit per pixel", when in reality the bitmaps are 1 *byte* per pixel (8 bits).
The description of the bitmap's size was also somewhat unclear.

ass.h: clarify comments on struct ass_image

---

.github/workflows/ghci.yml

Depends on https://github.com/libass/libass-tests/pull/3
It fails the CI run with the `leaks` check as expected. However, the redirecting to silence `fuzz`’s *(originally `profile`’s)* detailed output also removes `leaks` report, so there are no immediately visible details on what went wrong and for some reason the fialing CI job gets stuck in the following cleanup steps. See e.g.: https://github.com/TheOneric/libass/actions/runs/5661487504/job/15339487365 or the preceding runs.  
**EDIT:** so the output of the `test` step isn't even available anymore thanks to getting stuck, but basically it just told you the crash tests did indeed crash (only for the run with `leaks`) but without any details on why, then `make check` exited and our manually defined steps were done with and it went to …

ci/gha: detect leaks on MacOS

---

.github/workflows/meson.yml
meson.build

As brought up in the threading PR #793 
@astiob, do you know which flags we need with MSVC to enable similar errors as for GCC-like compilers?

ci/gha/meson: build both static and dynamic lib on Windows

---

libass/ass_filesystem.c

ass_filesystem: fix invalid memory copy in append_tail

---

libass/ass_fontconfig.c

When the used config is completely devoid of fonts FcFontSort will attempt to allocate an empty set and return it while still setting the result to invalid.
Similar case as fixed in 6e83137cdbaf4006439d526fef902e123129707b.

fontconfig: fix minor memory leak in fallback font selection

---

.github/workflows/meson.yml

It has been upgraded to 24.04 which should be new enough.

ci/gha/meson: use ubuntu-latest directly for tarball test

---

fuzz/meson.build
meson_options.txt

This will allow to enable MSAN and i386 builds in oss-fuzz. See: https://github.com/kasper93/oss-fuzz/commit/2709d7fed5303a0601c6e7c85792a2ba58258119

meson: add support for oss-fuzz

---

libass/ass_render.c

For `offset.x`, `{\fnArial}a͉` seems to work as a test.
---
Glyphs within multiglyph clusters weren't adjusted correctly. In particular, for Burmese, HarfBuzz produces clusters that contain multiple glyphs laid out in a horizontal sequence, with large positive intra-cluster advances, which were not getting translated to vertical offsets by our \fay code, causing the later glyphs within the cluster to appear raised, as though forming a staircase.
Fixes: https://github.com/libass/libass/issues/887

Fix \fay with glyph clusters

---

libass/ass_render.c

All usual shadow-during-fade caveats apply, so I’m not _quite_ sure that this is wanted. But not applying fade at all seems only worse, no?

Apply \fade to BorderStyle 4 boxes
