libass/ass_bitmap.c, libass/ass_bitmap.h, libass/ass_cache.c, libass/ass_cache.h, libass/ass_cache_template.h, libass/ass_render.c, libass/ass_render.h
I thied to fix incorrect caching with different fonts but the same text line and got swallowed.
This is the result.
I hope it fixes at least #153.
=> Clean up bitmap combining

libass/ass_coretext.c, libass/ass_directwrite.c, libass/ass_font.c, libass/ass_fontconfig.c, libass/ass_fontselect.c, libass/ass_fontselect.h, test/test.c
Untested on OS X. Please test.
=> Substitutions and some fixes

configure.ac
Hi,
Attached are several patches that are currently applied to the VLC contrib version of libass.
Would appreciate if some or all of them could be applied upstream.
=> Forwarded patches from VLC contrib collection

libass/ass.c, libass/ass_render.c
Fix potential problem found by Coverity Scan and couple of errors found by -fsanitize=undefined.
=> Fix bunch of UB

libass/ass_render.c, libass/ass_render.h
That's trivial fix of aforementioned problem with incorrect deallocation.
=> Fix problem with ass_frame_unref()

README.md
Change links of VSFilters in README.md to new address or maintained forks.
=> Update VSFilter links

libass/ass_font.c
We used to do a lot of work to get freetype to imitate VSFilter's font-metrics handling. Instead, we now just duplicate its behavior directly early on. This seems to produce the same behavior as we had with previous FreeType versions (matching VSFilter) in much less code.
=> font: simplify metrics handling; fixes #361

configure.ac, libass/ass_shaper.c
tbh this duplication feels a little excessive but it's what hb wants out of us so 🤷‍♀️
=> ass_shaper: fix harfbuzz deprecation warning

libass/ass_parse.c, libass/ass_utils.c, libass/ass_utils.h
See commit messages for details; these reduced CPU usage on a real script I was sent by over 30%.
=> A couple small optimizations

libass/ass_fontconfig.c, libass/ass_fontselect.c, libass/ass_parse.c
See individual commit messages; most notably the last commit reverts a mistake of mine from last year (which thankfully never made it into a release).
=> Assorted bug fixes

libass/ass_bitmap.h, libass/ass_blur.c, libass/ass_func_template.h, libass/x86/blur.asm, libass/x86/utils.asm
My initial blur algorithm was overcomplicated due to (mostly arbitrary) decision to use filters not larger than 9-tap. That leads to use of an additional stage (prefilter) and irregular main filter pattern (1235, 1246). Over time I realized that it's not worth it and did some experiments. And now it's time to apply my new understanding to libass!
Also now I have AVX2-capable CPU and more practice with AVX2 assembly so there are some improvements in that area. Overall this new algorithm should have slightly better precision and performance than old.
=> Blur algorithm overhaul

libass/ass_parse.c, libass/ass_render.c, libass/ass_render.h, libass/ass_shaper.c
The Holy Grail of glyph runs is (almost) here. This wasn’t even hard, so far.
My next PR will be karaoke that makes use of the early-detected runs.
=> Split glyph runs early and fix some run splitting bugs

libass/ass_coretext.c
CoreText's "family name" can use TT_NAME_ID_TYPOGRAPHIC_FAMILY names, which we ignore for compatibility with VSFilter. As a result, fallback returns a family name that we then fail to find, and fallback fails.
Return a fuller name (fullname or postscriptname as appropriate) instead, which should be more reliable.
This fixes broken fallback on kanji from Arial/Helvetica to Hiragino Sans on my machine. The current code returns “Hiragino Sans”, which is a TT_NAME_ID_TYPOGRAPHIC_FAMILY name, we fail to select it, and I end up seeing tofu. The new code returns “HiraginoSans-W3”, which works.
=> coretext: return full/PostScript name on fallback

libass/Makefile.am, libass/ass_bitmap.c, libass/ass_bitmap.h, libass/ass_func_template.h, libass/ass_rasterizer.c, libass/ass_rasterizer_c.c, libass/ass_render.c, libass/x86/be_blur.asm, libass/x86/blend_bitmaps.asm, libass/x86/blur.asm, libass/x86/rasterizer.asm, libass/x86/utils.asm
This is the result of my tinkering with checkasm branch (my continuation of it is [here](https://github.com/MrSmile/libass/commits/checkasm)). There was some problematic assembly, which already has its checkasm tests, so I've tried to improve it. This PR is getting rid of 64-bit only, avx2 slower than sse2 assembly, while improving performance in general.
=> Asm overhaul

libass/ass.c
Commit b3339152db5b80991966911fe2efc8a6174b0071 explicitly defaulted
ScaledBorderAndShadow to "yes" for files with custom format lines to
allow a subsequent commit to change the global default to "no" to match
VSFilter, while trying to avoid breaking files expecting libass' prior
default. This commit also changed the fallback ASS event format line to
use 'Name' instead of 'Actor' to match what we are actually parsing,
what Aegisub is emitting and what is used in the "specification".
However, as it turns out, PopSub and files _converted_ by VSFilter
actually do use 'Actor', but are expecting the VSFilter-compatible
default "no".
Thus, treat both variants as synonyms in event parsing and format line
comparison. There is a slight inconsistency here, that _Style_ format
lines which use …
=> Treat 'Name' and 'Actor' as synonyms in format lines

.gitignore, configure.ac, libass/Makefile.am, libass/ass_utils.c
Another part of checkasm branch. Unrelated to checkasm but useful.
=> Bunch of miscellaneous commits from checkasm branch

libass/ass.c, libass/ass.h, libass/ass_render.c, libass/ass_shaper.c, libass/ass_shaper.h
=> Emulate VSFilter’s bidi and \fay by default; add an ASS_Feature for better bidi and shaping

libass/ass.c
Fixes: https://github.com/libass/libass/issues/670
=> Don't trim trailing spaces from string fields

libass/ass_bitmap_engine.c
https://en.cppreference.com/w/c/language/struct_initialization
=> vc: fix struct init error. supported since c23

libass/ass_shaper.c
Full explanation in the big commit message.
=> Bidi: take into account all kinds of bidi paragraph separators

libass/ass_font.c
Fixes: https://github.com/libass/libass/issues/634
Fixes: https://github.com/mpv-player/mpv/issues/13322
=> font: prefer full-Unicode cmaps to BMP-only ones

libass/ass_directwrite.c
Fixes: https://github.com/libass/libass/issues/744
The code is fairly clear, but I guess I want a second opinion on whether ignoring the family name entirely is Good Enough.
=> directwrite: query GDI-enumerated fonts by full name, not family name

libass/x86/x86inc.asm
Updated to https://code.videolan.org/videolan/x86inc.asm/-/commit/04f14f431ce07ca349b5d87c9e5930f5950cf712
Related https://github.com/libass/libass/issues/742
=> x86: update x86inc.asm

README.md
Information about the format and to a lesser degree also other ASS implementations seem more relevant than a selection of some libass users to me
=> readme: move related projects into wiki; update VSFMod status

libass/ass_shaper.c
This was pointed out in #784, and I realized the remaining work that needed doing here was pretty minimal.
Most of our allocation and destruction of harfbuzz objects has been streamlined since #566 was filed, so checking for singleton returns was all that was left.
=> ass_shaper: check for singleton returns from harfbuzz; fixes #566

compare/image.c
I've tried to trigger all necessary colorspace conversions. It works on several samples that I created, but it certainly not a full set of possible PNG variants. So, more testing is welcome, especially with different paletted versions.
=> compare: add support for a wider PNG range

.github/workflows/ghci.yml, README.md, libass/ass_utils.h
See prior discussion in #820 and #822
Feel free to suggest other names for the macro
=> Verify assumed call requirements in CI builds

configure.ac, libass/ass_coretext.c
Should fix https://github.com/libass/libass/issues/837 (pending confirmation from OP).
=> Actually fix build on Mac OS X 10.5

fuzz/fuzz.c
In https://github.com/google/oss-fuzz/pull/12687 we’ve found out OSS_Fuzz currently reports pretty bad coverage for our corpus appearing to not even covering some basic override tags listed in the dictionary.  
To speed up the fuzzer and avoid the unhelpful time-out reports popping up occasionally (which due to CIFuzz deciding to abort on the first time out, also make the former unusable for us), just setting a size limit for testcases seems like the easiest option (apart from figuring out a good cutoff). However, while AFL and libFuzzer support CLI flags to limit the size of generated test cases, OSS Fuzz supports more engines and it’s `option` file apparently also only contains engine-specific settings  meaning we’d have to set it for all current and future engines.  
[OSS-Fuzz docs …
=> fuzz: optionally reject too large files and OSS-Fuzz observations

.github/workflows/meson.yml, Makefile.am, Makefile_util.am, checkasm/checkasm.h, checkasm/meson.build, compare/compare.c, compare/image.c, compare/meson.build, fuzz/fuzz.c, fuzz/meson.build, fuzz/writeout.c, meson.build, meson_options.txt, test/meson.build
Adds tests for meson builds in CI.
=> Tests in meson

.github/workflows/ghci.yml, .github/workflows/meson.yml
These runners are now available to free projects.
=> ci: enable ARM linux builds
